-- 코드를 입력하세요
WITH REST_INFO_WITH_RANK AS (
    SELECT *, ROW_NUMBER() OVER(PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RNK
    FROM REST_INFO
)

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO_WITH_RANK
WHERE RNK = 1
ORDER BY 1 DESC;