-- 코드를 작성해주세요
WITH GRADE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT G.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM GRADE G
    JOIN HR_EMPLOYEES HE ON G.EMP_NO = HE.EMP_NO 
    LEFT JOIN HR_DEPARTMENT HD ON HE.DEPT_ID = HD.DEPT_ID
ORDER BY G.SCORE DESC
LIMIT 1
