-- 코드를 작성해주세요
SELECT HD.DEPT_ID, HD.DEPT_NAME_EN, ROUND(AVG(HE.SAL)) AS AVG_SAL
FROM HR_EMPLOYEES HE LEFT JOIN HR_DEPARTMENT HD ON HE.DEPT_ID = HD.DEPT_ID
GROUP BY HD.DEPT_ID, HD.DEPT_NAME_EN
ORDER BY 3 DESC;